name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn prisma:generate
      - run: yarn build
      - run: yarn test:e2e
        env:
          # Provide dummy secrets if needed
          NEXTAUTH_SECRET: testsecret
          NEXTAUTH_URL: http://localhost:3000